<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TypeProvider.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.TypeProviders.SDK" Version="8.11.0" />
    <PackageReference Include="FSharp.Control.TaskSeq" Version="1.1.1" />
    <PackageReference Include="Parquet.Net" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parquet.TypeProvider.Runtime\Parquet.TypeProvider.Runtime.fsproj" />
  </ItemGroup>

</Project>
