<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Parquet.TypeProvider</PackageId>
    <Description>A high-performance F# Type Provider for Apache Parquet files, powered by Parquet.Net</Description>
    <NoWarn>$(NoWarn);NU5100</NoWarn>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ParquetRowContext.fs" />
    <Compile Include="ParquetReaderCore.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Control.TaskSeq" Version="1.1.1" />
    <PackageReference Include="Parquet.Net" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net8.0\Parquet.TypeProvider.DesignTime.dll" PackagePath="typeproviders\fsharp41\net8.0" Pack="true" Visible="false" Condition="Exists('..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net8.0\Parquet.TypeProvider.DesignTime.dll')" />
    <None Include="..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net8.0\FSharp.TypeProviders.SDK.dll" PackagePath="typeproviders\fsharp41\net8.0" Pack="true" Visible="false" Condition="Exists('..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net8.0\FSharp.TypeProviders.SDK.dll')" />
    <None Include="..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net9.0\Parquet.TypeProvider.DesignTime.dll" PackagePath="typeproviders\fsharp41\net9.0" Pack="true" Visible="false" Condition="Exists('..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net9.0\Parquet.TypeProvider.DesignTime.dll')" />
    <None Include="..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net9.0\FSharp.TypeProviders.SDK.dll" PackagePath="typeproviders\fsharp41\net9.0" Pack="true" Visible="false" Condition="Exists('..\Parquet.TypeProvider.DesignTime\bin\$(Configuration)\net9.0\FSharp.TypeProviders.SDK.dll')" />
  </ItemGroup>

</Project>
